language: node_js
node_js:
  - "0.12"
before_install:
  - "cd lablancas/twitter/.npm/package; cp npm-shrinkwrap.json package.json; npm install; cd ../../../../"
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh"